---
title: "Corporate Finance"
subtitle: "Lecture 12: Final Exam Information"
footer: "Lecture 12: Final Exam Information"
---

## General information {.smaller}

- The duration is 120 minutes and the exam covers the whole content of
  the course.

- You are permitted to use a calculator. No computers or mobile phones
  are allowed.

- The exam is closed book. Some essential formulas are given in the
  formula sheet attached at the end of the exam paper.

- The final exam is worth 70% of the overall grade.

  - The rest is the mid-term assignment grade (20%) and the myfinance
    lab homeworks (10%).

- Students need a minimum grade of 8 in the final exam and an overall
  grade of at least 10 to pass the course.

## Details on the final exam {.smaller}

- **Bring your calculator, HB pencil, pen, eraser, and a ruler.**

- Part 1 (worth 10 points): 15 multiple-choice questions worth $2/3$
  points each.

  - You must select the most appropriate response. There is just one
    correct answer per question.\

  - You must use a hard black (HB) pencil to fill in the responses on
    the multiple choice answer sheet.

- Part 2 (worth 10 points): Open and calculation questions.

  - Report the main calculation steps and justify all your responses.

  - Report all numbers with four decimals and percentages with two
    decimals.

## How to study? {.smaller}

- **Take** last year's exam that is available with solutions in the
  course content section on blackboard.

  - The final exam will be of similar length and format. It can cover
    questions on **any topic of the course.**

- **Review and study** all the lecture slides and recordings, your
  notes, corresponding book chapters, exercise sheets, last year's exam,
  homeworks, and Q&A forum posts.

  - You can already review your past homework attempts and the
    multimedia library and the study plan contain many more exercises to
    practice.

  - All homeworks will open again after the due date of Homework 11
    until the final.

- **Post** any course-related questions in the **Q&A forum on
  blackboard**.
